### ISSUE TITLE
効果あり（悪い効果）を追加

### ISSUE THREAD

**Issue by daimoriwaki** [CyberAgentAILab/EBPMDB#55]
https://github.com/CyberAgentAILab/EBPMDB/issues/53
これが解決されたときに、READMEも直す

**Comment by takaakikeda** [comment]
効果あり（悪い効果）について修正が必要なドキュメントをリスト化しました。
https://docs.google.com/spreadsheets/d/1ni76fzWULKIPhvF8enuRIjNFsd7hFjJtWSpHrgaZhKU/edit?usp=sharing

**Comment by daimoriwaki** [comment]
@takaakikeda ありがとうございます！！！

**Comment by daimoriwaki** [comment]
議論の結果、以下のように修正したいと思います。
簡単に @takaakikeda  との議論の内容をまとめます。
- 現状のレビューを全て確認した結果、悪い効果とすべきものはすべて政策の主要なアウトカム指標ではない別の指標での悪化を指摘していた（例：医療費ゼロ=>メインの目的である健康に関する部分ではなく無駄な医療費の増加、学校の閉鎖=>メインの目的はコロナの感染抑止だったが母親の悩みや学生の肥満が増加）
- 従って逆効果とは言えず、むしろ副次的な悪影響として整理すべき
![Untitled](https://user-images.githubusercontent.com/29854085/207736631-4d167353-0558-490f-9061-705e46ce32c8.png)
コメントあれば、以下スレッドにお願いします。週明けくらいから実装入ろうと思います。

**Comment by RyoMogi** [comment]
分野にもよるかと思いますが、その分析のメイン以外の変数との関係については載せなくてもいいのではないでしょうか？メイン以外の変数との関係は分析的にロバストなものなのか結構危ない気がします。アウトカムとして載せずに、注書きくらいで十分かと思うのですが、いかがでしょうか。

**Comment by daimoriwaki** [comment]
@RyoMogi ありがとうございます。少し説明が不足していました。ネガティブな効果を主張する論文の多くは、「本来の目的ではない変数」を分析のメインにおき「本来の目的の変数」については分析していないものが多数あります。
こうした論文は医療分野がほとんどでたとえば、節電と熱中症、コロナによる学校閉鎖と肥満など、政策の目的であった電力使用の抑制や感染症拡大との関係ではなく副次的な作用を論文のメインテーマにしています。

少子化対策分野だと、以下の一本がネガティブな効果を主張しています。
https://cyberagentailab.github.io/EBPMDB/doc/document110/
この論文の場合、問題行動の増加を副作用とするのはあまり違和感はないかなと思いますが、一方で、保育所利用が問題行動の抑制をメインの目的にしているのであれば本当の意味での逆効果にあたるので効果なしのままでもいいかもしれません。

**Comment by RyoMogi** [comment]
なるほど！「本来の目的」とは論文の、ではなく政策のという意味ですね。コロナによる学校閉鎖など政策の目的が明確な場合は、確かに副次的な悪影響として整理してもいいかもしれないですね。ただ確かに仰る通り、育児休業など、どれが政策の主眼なのかがわかりにくいものの取り扱いは難しいかもですね。

**Comment by daimoriwaki** [comment]
> なるほど！「本来の目的」とは論文の、ではなく政策のという意味ですね。

その通りです。説明が足りずすみません。

> ただ確かに仰る通り、育児休業など、どれが政策の主眼なのかがわかりにくいものの取り扱いは難しいかもですね。

こちらは、少子化については一旦現行のまま「効果なし」としつつ、意見がある場合はその都度議論すると言う形にできればと思います。
